version: "{build}"

platform: x64

branches:
  only:
    - master

skip_tags: true

clone_folder: c:\gopath\src\github.com\ernado\stun

environment:
  GOPATH: c:\gopath
  GOVERSION: 1.9.1
  TEST_EXTERNAL: 1

install:
  - go version
  - go get -v -t .

build_script:
  - go test -v .
